import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import Cursor from "./Cursor";
import { Toaster } from "sonner";

const jost = Jost({ subsets: ["latin"], variable: "--font-jost" });

export const metadata: Metadata = {
  title: "Marketing Tribe",
  description: "Generated by Marketing Tribe",
  icons: {
    icon: "/favicon.png", // ✅ Path to your favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.variable} antialiased`}>
        {children}
        <Cursor />
        <Toaster  />
      </body>
    </html>
  );
}
